# Generated by Django 4.2.3 on 2023-07-27 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Unidades', '0001_initial'),
        ('demandaProdutos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subunidade',
            name='carrinho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subUnidade_carrinho', to='demandaProdutos.carrinho'),
        ),
        migrations.AddField(
            model_name='subunidade',
            name='gestorSubUnidade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subunidade',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subUnidade_pedido', to='demandaProdutos.pedido'),
        ),
    ]
