# Generated by Django 4.2.4 on 2023-09-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandaProdutos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arquivo',
        ),
    ]
