# Generated by Django 4.2.4 on 2023-10-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandaProdutos', '0004_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='is_stiadmim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
